### PR TITLE
[FIX] resolve numpy2 compatibility related to ambiguity when broadcasting in np.solve

### LINKED ISSUE #4309: numpy 2 test workflow failures
~See here:~
~https://github.com/nilearn/nilearn/actions/runs/8137823574/job/22237131770?pr=4306#step:6:5109~

~seem to be a more of a pandas 3.0~

~FAILED nilearn/datasets/tests/test_func.py::test_fetch_surf_nki_enhanced~
~FAILED nilearn/plotting/tests/test_matrix_plotting.py::test_show_event_plot~

~Errors:~

~("'DataFrame' object has no attribute '_mgr'")~
~ValueError: Unable to avoid copy while creating an array from given array.~

See [below for an update](https://github.com/nilearn/nilearn/issues/4309#issuecomment-1989166590)

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4309

Changes proposed in this pull request:

- implemented recommendations from https://numpy.org/devdocs/release/2.0.0-notes.html#removed-ambiguity-when-broadcasting-in-np-solve

### CODE REVIEW

**Comment by Remi-Gau** [comment]
The remaining failing test should be fixed by #4349.

**Comment by bthirion** [comment]
Numpy2 compatibility still breaks somewhere else...

**Comment by Remi-Gau** [comment]
OK this fail is related to some pandas 3.0 dependency...

**Comment by bthirion** [comment]
Do you want to address it ?

**Comment by Remi-Gau** [comment]
Sure but not in this PR.

**Review by bthirion — APPROVED** [review]
