### ISSUE TITLE
GroupSparseCovariance doesn't work with scikit-learn master

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1724]
Running the examples on scikit-learn master gives the following:

```
/home/varoquau/dev/nilearn/examples/03_connectivity/plot_multi_subject_connectome.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/varoquau/dev/nilearn/doc/sphinxext/sphinx_gallery/gen_rst.py", line 472, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 3, in <module>
  File "/home/varoquau/dev/nilearn/nilearn/connectome/group_sparse_cov.py", line 948, in fit
    classifier=False
  File "/home/varoquau/dev/scikit-learn/sklearn/model_selection/_split.py", line 1957, in check_cv
    "or an iterable. Got %s." % cv)
ValueError: Expected cv as an integer, cross-validation object (from sklearn.model_selection) or an iterable. Got None.
```

**Comment by kchawla-pi** [comment]
Looking into it.
How has this not been caught by the tests?
How did you find it?
Is there a hole in the tests that should be filled?

**Comment by kchawla-pi** [comment]
I got this:
```
Traceback (most recent call last):
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/examples/03_connectivity/plot_multi_subject_connectome.py", line 119, in <module>
    plotting.show()
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/nilearn/plotting/img_plotting.py", line 47, in show
    plt.show()
  File "/home/kshitij/anaconda3/envs/nilearn-py34/lib/python3.4/site-packages/matplotlib/pyplot.py", line 244, in show
    return _show(*args, **kw)
  File "/home/kshitij/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.3684.100/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 25, in __call__
    manager.show(**kwargs)
  File "/home/kshitij/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.3684.100/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 107, in show
    self.canvas.show()
  File "/home/kshitij/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.3684.100/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 62, in show
    self.figure.tight_layout()
  File "/home/kshitij/anaconda3/envs/nilearn-py34/lib/python3.4/site-packages/matplotlib/figure.py", line 1754, in tight_layout
    rect=rect)
  File "/home/kshitij/anaconda3/envs/nilearn-py34/lib/python3.4/site-packages/matplotlib/tight_layout.py", line 322, in get_tight_layout_figure
    max_nrows = max(nrows_list)
ValueError: max() arg is an empty sequence
```

**Comment by kchawla-pi** [comment]
I keep getting the error I got instead of the one you got. 
commit 19e8119672360df38f6afd7b28b8559bd5b8ef35 by jerome  gives this:

```
/home/kshitij/anaconda3/envs/nilearn-py34/bin/python /home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/examples/03_connectivity/plot_multi_subject_connectome.py
Traceback (most recent call last):
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/examples/03_connectivity/plot_multi_subject_connectome.py", line 11, in <module>
    from nilearn import plotting
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/nilearn/plotting/__init__.py", line 47, in <module>
    from .html_connectome import view_connectome
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/nilearn/plotting/html_connectome.py", line 7, in <module>
    from .html_surface import (add_js_lib, SurfaceView, to_plotly,
ImportError: cannot import name '_encode'

Process finished with exit code 1
```

What do you mean when you say "running the example on skl master"? Aren't we using that anyway?
Regardless, we shouldn't be getting any error of any kind; however I haven't been able to replicate the error you are getting.
Will continue this later.

**Comment by kchawla-pi** [comment]
I was doing a git bisect and stopped at the above commit cuz it was time to sleep. Not that I pin-pointed that commit as the culprit.
It seems these issues are not related to our latest alpha release.

**Comment by jeromedockes** [comment]
could not reproduce

> Running the examples on scikit-learn master gives the following:

could not reproduce after installing scikit-learn commit 7ba7a4a1c254d5be939ae3472583232332ec3871 (august 6)

**Comment by jeromedockes** [comment]
> I got this:

could not reproduce with matplotlib 1.5.1 nor 2.2.2

**Comment by kchawla-pi** [comment]
Gael, is this related to our alpha push? (I had assumed that in the beginning but now I don't think it is).

**Comment by kchawla-pi** [comment]
Manage to replicate the error using nilearn & skl master.

**Comment by kchawla-pi** [comment]
Huh. 
I get the error @GaelVaroquaux gets when running from the terminal, not when using Pycharm's run function. 
I get the matplotlib error when I run the example using pycharm's run function, not when I run it from the terminal.

**Comment by kchawla-pi** [comment]
**sklearn v0.19.1**: The default value for `cv` in `/sklearn/model_selection/_split.py` is `cv=3`
**sklearn v0.20.dev0**: The default value for `cv` in `/sklearn/model_selection/_split.py` is `cv='warn'`

**Comment by kchawla-pi** [comment]
In **sklearn v0.19.1**:
The default value for `cv` in `/sklearn/model_selection/_split.py` is `cv=3` . It then checks if the passed in value of `cv` is `None`, and if it, it assigns `cv = 3`.

In **sklearn v0.20.dev0**: 
The default value for `cv` in `/sklearn/model_selection/_split.py` is `cv='warn'` &
when 'cv` == 'warn', `cv` is assigned the value of `3`. 
However, there is no check for if `cv` is `None`.

This is breaking code compatibility with older version.

The most straightforward way for us to fix this in the Nilearn example would be to assign a value to cv during `GroupSparseCovarianceCV` instance creation.

This might be worth an issue in sklearn.

**Comment by kchawla-pi** [comment]
Filed: https://github.com/scikit-learn/scikit-learn/issues/11760

**Comment by kchawla-pi** [comment]
What do you think @GaelVaroquaux . Do you want to do something about this?

**Comment by kchawla-pi** [comment]
SKL acknowledged the bug. I submitted a PR to fix it & so did another. Should be done with soon enough.

**Comment by kchawla-pi** [comment]
The default for cv will be changed to a 5 eventually. This mght be a good time to explicitly set cv=3 in our examples.

**Comment by kchawla-pi** [comment]
SKL has merged the fix. I will check later if this is still an issue. 
@GaelVaroquaux can you check as well? Should we change the examples?

**Comment by kchawla-pi** [comment]
I am not getting the error any longer. I will close this. @GaelVaroquaux you check as well, and if you are still getting the error we'll reopen this.

**Comment by EcoHub** [comment]
dear @kchawla-pi you said that "The most straightforward way for us to fix this in the Nilearn example would be to assign a value to cv during GroupSparseCovarianceCV instance creation."
please how to access to GroupSparseCovarianceCV instance creation.
I am using scikit-learn-0.21.3 (I had problems with scikit-learn 0.22)
