### ISSUE TITLE
plot_matrix does not work with mpl 3.0.2

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#2045]
On nilearn 0.5.0b
calling matrix_plotting spits an error

~/mygit/nilearn/nilearn/plotting/matrix_plotting.py in fit_axes(ax)
     10     fig = ax.get_figure()
     11     renderer = get_renderer(fig)
---> 12     ylabel_width = ax.yaxis.get_tightbbox(renderer).inverse_transformed(
     13         ax.figure.transFigure).width
     14     if ax.get_position().xmin < 1.1 * ylabel_width:

AttributeError: 'NoneType' object has no attribute 'inverse_transformed'

This seems to be unrelated to what I'm doing. Sounds like a version incompatibility.

**Comment by kchawla-pi** [comment]
Does it happen with Nilearn 0.5.2 as well?

**Comment by jeromedockes** [comment]
I haven't managed to reproduce it, neither with 0.5.2 nor 0.5.0.b
I think the figure might not have been rendered yet. can you provide an example to reproduce, and specify which matplotlib backend you are using?

**Comment by bthirion** [comment]
OK. Closing in favor of #2049
