### ISSUE TITLE
Nilearn usage example 8.2.11 fetches incorrect neurovault data

### ISSUE THREAD

**Issue by AkiNikolaidis** [nilearn/nilearn#1836]
Hello!

When using the [Jupyter Notebook version of exercise 8.2.11](http://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py), and running the second cell, the code uses datasets.fetch_neurovault_motor_task() where I believe it should be using datasets.fetch_neurovault()? 

```
from nilearn import datasets
motor_images = datasets.fetch_neurovault_motor_task()
```

And it returns the following output: 

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-de7b63d2b43a> in <module>()
      1 from nilearn import datasets
      2 
----> 3 motor_images = datasets.fetch_neurovault_motor_task()
      4 stat_img = motor_images.images[0]

AttributeError: module 'nilearn.datasets' has no attribute 'fetch_neurovault_motor_task'

>

**Comment by KamalakerDadi** [comment]
No it is the right one ``datasets.fetch_neurovault_motor_task()```. THis is something added from 0.5.0 alpha.
Have a look at the changelog in http://nilearn.github.io/whats_new.html 0.5.0alpha.
If you are using that version. Then you should be able to get that.

Can you let us know your version ?

**Comment by KamalakerDadi** [comment]
>AttributeError: module 'nilearn.datasets' has no attribute 'fetch_neurovault_motor_task'

@AkiNikolaidis Could you please check with latest version 0.5 ?

**Comment by KamalakerDadi** [comment]
Closing this one. 

Please let us know if the problem still persists after upgrading to 0.5.0
